---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: src/data/info.md
  label: Info Page
  read_only: false
- type: document
  path: src/data/config.json
  label: Site Info
- type: heading
  label: Config
- type: directory
  path: src/posts
  label: Blog Posts
  create: documents
  match: "**/*"
  new_doc_ext: md
- type: heading
  label: Content
upload_dir: src/static
public_path: src/static
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
